name: first-time-setup
run-name: Setup

on:
  create:

permissions: 
  actions: write
  checks: write
  contents: write

jobs:
  first-time-setup:
    # Ensure this job does not run:
    # - on the template repository 
    # - when forked
    # - it has already been executed once
    if: ${{ !github.event.repository.is_template && !github.event.repository.fork && github.run_number == 1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute the bootstrap script
        run: CI=true JURISDICTION_NAME="$(echo ${{ github.event.repository.name }} | sed 's/openfisca-//')" REPOSITORY_URL="${{ github.repositoryUrl }}" ./bootstrap.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Adapt template automatically"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
