name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ assigned, opened, reopened, synchronize, ready_for_review ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: "./.github/workflows/build.yml"

  test-yaml:
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      
      - name: Cache build
        id: restore-build
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ github.sha }}
      
      - run: make test

  test-api:
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      
      - name: Cache build
        id: restore-build
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ github.sha }}
      
      - name: Test the Web API
        run: "${GITHUB_WORKSPACE}/.github/test-api.sh"
